<br><br>
<div class="row">
    <div class="col-lg-12">
        <div class="jumbotron">
            <h2 class="text-center">
                <?php echo $msg; ?>
            </h2>
            <center>
                <h4 id="redirect"></h4>
            </center>
        </div>
    </div>
    
</div>
<br>
<br>
<br>
<br>

<div class="row">
    <div class="col-sm-offset-3 col-sm-6">
    <fieldset>
        <form id="formulario">
        
            
        </form>
        
    </fieldset>

    </div>
</div>
