<br><br>
<div class="row">
    <div class="col-lg-12">
        <div class="jumbotron">
            <h2 class="text-center">
                <?php echo $msg; ?>
            </h2>
        </div>
    </div>
    
</div>
<br>
<br>
<br>
<br>

<div class="row">
    <div class="col-sm-offset-3 col-sm-6">
    <fieldset>
        <form method="post">
        
            
        </form>
    </fieldset>

    </div>
</div>
