<br><br>
<div class="container-fluid">
    <div class="row bg-success">
        <div class="col-md-12">
            <br>
            <div class="row">
                <div class="col-md-2">
                    <h4><strong>Admin</strong></h4>
                </div>
                <div class="col-md-8"></div>
                <div class="col-md-2">
                    <h4><strong>
                    <div id="redirect"></div>
                    </strong></h4>
                </div>
            </div>
            <br>
        </div>
    </div>
</div>
<br><br>
<div class="row">
    <div class="col-lg-12">
        <div class="jumbotron">
            <h2 class="text-center">
                <?php echo $msg; ?>
            </h2>
            <center>
                <h4 id="redirect"></h4>
            </center>
        </div>
    </div>
    
</div>

<div class="row">
    <div class="col-md-4">
        <center>
            <h2>Menú Lateral</h2>
        </center>
        <hr>
        <ul>
            <li><a href="javascript:void(0)">Menú ...</a></li>
            <li><a href="javascript:void(0)">Menú ...</a></li>
            <li><a href="javascript:void(0)">Menú ...</a></li>
            <li><a href="javascript:void(0)">Menú ...</a></li>
            <li><a href="javascript:void(0)">Menú ...</a></li>
            <li><a href="javascript:void(0)">Menú ...</a></li>
            <li><a href="javascript:void(0)">Menú ...</a></li>
            <li><a href="javascript:void(0)">Menú ...</a></li>
            <li><a href="javascript:void(0)">Menú ...</a></li>
            <li><a href="javascript:void(0)">Menú ...</a></li>
            <li><a href="javascript:void(0)">Menú ...</a></li>
            <li><a href="javascript:void(0)">Menú ...</a></li>
            <li><a href="javascript:void(0)">Menú ...</a></li>
            <li><a href="javascript:void(0)">Menú ...</a></li>
            <li><a href="javascript:void(0)">Menú ...</a></li>
            <li><a href="javascript:void(0)">Menú ...</a></li>
            <li><a href="javascript:void(0)">Menú ...</a></li>
            <li><a href="javascript:void(0)">Menú ...</a></li>
            <li><a href="javascript:void(0)">Menú ...</a></li>
            <li><a href="javascript:void(0)">Menú ...</a></li>
            <li><a href="javascript:void(0)">Menú ...</a></li>
            <li><a href="javascript:void(0)">Menú ...</a></li>
            <li><a href="javascript:void(0)">Menú ...</a></li>
            <li><a href="javascript:void(0)">Menú ...</a></li>
            <li><a href="javascript:void(0)">Menú ...</a></li>
            <li><a href="javascript:void(0)">Menú ...</a></li>
            <li><a href="javascript:void(0)">Menú ...</a></li>
            <li><a href="javascript:void(0)">Menú ...</a></li>
            <li><a href="javascript:void(0)">Menú ...</a></li>
        </ul>
    </div>
    
    <div class="col-md-8">
        <div class="row">
            <div class="col-md-6">
                <center>
                <img src="/staticfiles/imgs/php.jpg" class="img-responsive" alt="">
                </center>
            </div>
            <div class="col-md-6">
                
                <p class="text-justify">Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam veritatis laboriosam quidem! Quaerat unde fuga repellat! Dolore aspernatur aliquam, provident asperiores sequi alias dignissimos optio doloribus atque distinctio, soluta ullam.</p>
                <p class="text-justify">Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam veritatis laboriosam quidem! Quaerat unde fuga repellat! Dolore aspernatur aliquam, provident asperiores sequi alias dignissimos optio doloribus atque distinctio, soluta ullam.</p>
                
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <center>
                <img src="/staticfiles/imgs/php-banner.png" class="img-responsive" alt="">
                <br>
                </center>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <img src="/staticfiles/imgs/php.jpg" class="img-responsive" alt="">
                <hr>
                <p class="text-justify">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Doloremque explicabo ipsam odit ex, fuga esse eligendi! Sint labore, placeat architecto fugiat laudantium quam id accusantium nobis voluptatibus voluptate molestias voluptates!</p>
            </div>
            <div class="col-md-4">
                <img src="/staticfiles/imgs/php.jpg" class="img-responsive" alt="">
                <hr>
                <p class="text-justify">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Doloremque explicabo ipsam odit ex, fuga esse eligendi! Sint labore, placeat architecto fugiat laudantium quam id accusantium nobis voluptatibus voluptate molestias voluptates!</p>
            </div>
            <div class="col-md-4">
                <img src="/staticfiles/imgs/php.jpg" class="img-responsive" alt="">
                <hr>
                <p class="text-justify">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Doloremque explicabo ipsam odit ex, fuga esse eligendi! Sint labore, placeat architecto fugiat laudantium quam id accusantium nobis voluptatibus voluptate molestias voluptates!</p>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <center>
                <img src="/staticfiles/imgs/php-banner.png" class="img-responsive" alt="">
                <br>
                </center>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <img src="/staticfiles/imgs/php.jpg" class="img-responsive" alt="">
                <hr>
                <p class="text-justify">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Doloremque explicabo ipsam odit ex, fuga esse eligendi! Sint labore, placeat architecto fugiat laudantium quam id accusantium nobis voluptatibus voluptate molestias voluptates!</p>
            </div>
            <div class="col-md-4">
                <img src="/staticfiles/imgs/php.jpg" class="img-responsive" alt="">
                <hr>
                <p class="text-justify">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Doloremque explicabo ipsam odit ex, fuga esse eligendi! Sint labore, placeat architecto fugiat laudantium quam id accusantium nobis voluptatibus voluptate molestias voluptates!</p>
            </div>
            <div class="col-md-4">
                <img src="/staticfiles/imgs/php.jpg" class="img-responsive" alt="">
                <hr>
                <p class="text-justify">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Doloremque explicabo ipsam odit ex, fuga esse eligendi! Sint labore, placeat architecto fugiat laudantium quam id accusantium nobis voluptatibus voluptate molestias voluptates!</p>
            </div>
        </div>x


    </div>
</div>