<br><br>
<div class="row">
    <div class="col-lg-12">
        <div class="jumbotron">
            <h2 class="text-center">
                <?php echo $msg; ?>
            </h2>
        </div>
    </div>
    
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="row">
    <div class="col-lg-4 offset-lg-4">
        <h4>
            <ul class="menu">
                <li>
                <a href="<?php echo Link::path() . '?accion=login'  ?>">Login</a>
                </li>
                <li>
                <a href="<?php echo Link::path() . '?accion=table-json'  ?>">Response Json</a>
                </li>
                <li>
                <a href="<?php echo Link::path() . '?accion=table'  ?>">Consult</a>
                </li>
            </ul>
        </h4>
    </div>
</div>
