<br><br>
<div class="row">
    <div class="col-lg-12">
        <div class="jumbotron">
            <h2 class="text-center">
                <?php echo $msg; ?>
            </h2>
        </div>
    </div>
    
</div>
<br>
<br>
<br>
<br>

<div class="row">
    <div class="col-sm-offset-1 col-sm-10">

        <table id="table" class="table table-stripped table-border nowrap" style="width:100%">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>Edad</th>
                    <th>Cédula de Identidad</th>
                </tr>
            </thead>
        </table>

    </div>
</div>

