<br><br>
<div class="row">
    <div class="col-lg-12">
        <div class="jumbotron">
            <h2 class="text-center">
                <?php echo $msg; ?>
            </h2>
            <hr>
            <center>
                <h4 id="redirect"></h4>
            </center>
        </div>
    </div>
    
</div>
<br>
<br>
<br>
<br>

<div class="row">
    <div class="col-sm-offset-1 col-sm-10">

        <table id="table" class="table table-stripped table-border nowrap" style="width:100%">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Nombre</th>
                    <th>Descripción</th>
                    <th>Categoria</th>
                    <th>Usuario</th>
                </tr>
            </thead>
        </table>
        <br>
        <br>
    </div>
</div>

